'use client'

import { motion } from 'framer-motion'
import { 
  Video, 
  Brain, 
  Users, 
  Trophy, 
  BookOpen, 
  Target,
  Smartphone,
  BarChart3
} from 'lucide-react'

const features = [
  {
    icon: Video,
    title: 'Video-Based Learning',
    description: 'Learn through curated YouTube videos and interactive content designed for Filipino learners.',
    color: 'from-blue-500 to-blue-600'
  },
  {
    icon: Brain,
    title: 'AI-Powered Exams',
    description: 'Dynamic exams generated by OpenAI that adapt to your learning level and progress.',
    color: 'from-purple-500 to-purple-600'
  },
  {
    icon: Users,
    title: 'Study Groups',
    description: 'Join virtual study sessions and connect with fellow learners for collaborative learning.',
    color: 'from-green-500 to-green-600'
  },
  {
    icon: Trophy,
    title: 'Achievement System',
    description: 'Earn badges and certificates as you progress through your language learning journey.',
    color: 'from-yellow-500 to-yellow-600'
  },
  {
    icon: BookOpen,
    title: 'Personalized Learning',
    description: 'AI-driven recommendations and adaptive learning paths tailored to your needs.',
    color: 'from-red-500 to-red-600'
  },
  {
    icon: Target,
    title: 'Progress Tracking',
    description: 'Monitor your learning progress with detailed analytics and performance insights.',
    color: 'from-indigo-500 to-indigo-600'
  },
  {
    icon: Smartphone,
    title: 'Mobile First',
    description: 'Learn on the go with our responsive design that works perfectly on all devices.',
    color: 'from-pink-500 to-pink-600'
  },
  {
    icon: BarChart3,
    title: 'Performance Analytics',
    description: 'Get detailed insights into your learning patterns and areas for improvement.',
    color: 'from-orange-500 to-orange-600'
  }
]

export function FeaturesSection() {
  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
            Why Choose Our Platform?
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            We combine cutting-edge technology with proven learning methodologies to create 
            the most effective language learning experience for students worldwide, with special 
            focus on Filipino languages and Asian cultures.
          </p>
        </motion.div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="group"
            >
              <div className="relative p-6 bg-white rounded-xl shadow-sm border border-gray-200 hover:shadow-lg transition-all duration-300 hover:-translate-y-1">
                {/* Icon Background */}
                <div className={`w-12 h-12 rounded-lg bg-gradient-to-r ${feature.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300`}>
                  <feature.icon className="w-6 h-6 text-white" />
                </div>

                {/* Content */}
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600 text-sm leading-relaxed">
                  {feature.description}
                </p>

                {/* Hover Effect */}
                <div className="absolute inset-0 rounded-xl bg-gradient-to-r from-primary-500/5 to-secondary-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              </div>
            </motion.div>
          ))}
        </div>

        {/* Additional Info */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
          viewport={{ once: true }}
          className="mt-16 text-center"
        >
          <div className="bg-gradient-to-r from-primary-50 to-secondary-50 rounded-2xl p-8">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Global Platform with Filipino Expertise
            </h3>
            <p className="text-gray-600 max-w-2xl mx-auto mb-6">
              Our platform serves students worldwide while leveraging our deep expertise in Filipino 
              languages and Asian cultures. We provide culturally relevant content that's 
              educationally appropriate for learners of all backgrounds and age groups.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <span className="badge badge-primary">Age-Appropriate Content</span>
              <span className="badge badge-secondary">Cultural Relevance</span>
              <span className="badge badge-success">Local Context</span>
              <span className="badge badge-warning">Filipino Values</span>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
